### ISSUE TITLE
Add PyLadies code of conduct to PyLadies Bangkok website

### ISSUE THREAD

**Issue by gatukgl** [pyladiesbkk/pyladies-web#1]
In PyLadies Bangkok website, we need to add the [code of conduct](https://www.pyladies.com/CodeOfConduct/) to the website.

From the design [here](https://xd.adobe.com/spec/fa82faaf-c6f1-4ebd-7a2b-25ba6ba04ace-8cb3/), when we click at `Code of Conduct`, it would be better to go to `Code of Conduct` section.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/7122189/67104082-878b2900-f1f0-11e9-975b-37e1a62bea90.png">

**Comment by dollyjung** [comment]
Tukta request to do this ka
