### ISSUE TITLE
Add footer for website

### ISSUE THREAD

**Issue by Thoritie** [pyladiesbkk/pyladies-web#13]
In PyLadies Bangkok website, we need to have footer like this design,
From the design here, 

<img width="995" alt="Screen Shot 2562-10-18 at 23 06 01" src="https://user-images.githubusercontent.com/19608153/67110005-f621b400-f1fb-11e9-9161-15f8c7bb9ff8.png">

**Comment by nuttinee** [comment]
Boom ขอทำอันนี้นะคะ
