### ISSUE TITLE
Add PyLadies Gallery

### ISSUE THREAD

**Issue by gatukgl** [pyladiesbkk/pyladies-web#3]
In PyLadies Bangkok website, we want to see the gallery of event photos. This issue only for making the gallery works when we have more than 3 images, so that we can see more pictures. There would [be another issue](https://github.com/pyladiesbkk/pyladies-web/issues/17) that addresses adding pictures to the page

This is the first idea and the first [design](https://xd.adobe.com/spec/fa82faaf-c6f1-4ebd-7a2b-25ba6ba04ace-8cb3/) of the gallery.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/7122189/67103987-5b6fa800-f1f0-11e9-8632-bd5f31192068.png">

Also, you can build any kind of gallery and don't need to be the carousal like the exactly the same as the design.

**Comment by JaysZila** [comment]
จองจ้า

**Comment by Prontoshine** [comment]
add Gallery corousel #64
