### ISSUE TITLE
Change http to https

### ISSUE THREAD

**Issue by protal** [pyladiesbkk/pyladies-web#44]
fix Mixed content detected in Netlify
please change link below to https
In index.html:
- img http://via.placeholder.com/552x427
- img http://via.placeholder.com/524x343
- img http://via.placeholder.com/494x341
- img http://via.placeholder.com/582x375
- img http://via.placeholder.com/550x180
- img http://via.placeholder.com/154x154

**Comment by deezell1002** [comment]
ขอแก้
