### ISSUE TITLE
Translate PyLadies code of conduct to Thai

### ISSUE THREAD

**Issue by gatukgl** [pyladiesbkk/pyladies-web#5]
In PyLadies Bangkok website, it would be nice if we show PyLadies code of conduct in Thai. So we need to translate and place it instead of English version.

Here is the short version of code of conduct,

**English**
Please read http://www.pyladies.com/CodeOfConduct/
By signing up for this event you agree to abide by the PyLadies Code of Conduct because we are dedicated to providing a safe, inclusive, welcoming, and harassment-free space and experience for all members and guests, regardless of gender identity and expression, sexual orientation, disability, physical appearance, socioeconomic status, body size, ethnicity, nationality, level of experience, age, or religion (or lack thereof). The Code of Conduct exists because of that dedication. We do not tolerate harassment in any form and we prioritize marginalized people’s safety over privileged people’s comfort.

**Thai**
โปรดอ่าน http://www.pyladies.com/CodeOfConduct/
การสมัครมาร่วมกิจกรรมนี้แปลว่าคุณยอมปฏิบัติตามเงื่อนไขของ The PyLadies Code of Conduct เพราะเราตั้งใจที่จะสร้างสภาวะที่ปลอดภัย เปิดกว้าง และปราศจากการคุกคามต่างๆ สำหรับผู้ร่วมกิจกรรมทุกคน โดยไม่คำนึงถึง เพศสภาพ ความไร้ความสามารถ รูปลักษณ์ภายนอก สถานะทางสังคม ขนาดร่างกาย ชาติพันธุ์ เชื้อชาติ ประสบการณ์ อายุ และศาสนา โดยเราจะไม่ยอมให้การคุกคามเกิดขึ้นไม่ว่าทางใดก็ตาม นอกจากนั้นแล้วเรายังให้ความสำคัญกับความปลอดภัยของกลุ่มคนชายขอบมากกว่าสิทธิพิเศษกับกลุ่มคนใดกลุ่มหนึ่งอีกด้วย

Here is the long version of code of conduct,
**English**: https://www.pyladies.com/CodeOfConduct/

This is an example of the design for code of conduct section

<img width="783" alt="image" src="https://user-images.githubusercontent.com/7122189/67104651-84dd0380-f1f1-11e9-9a26-9657616d5113.png">

**Comment by dollyjung** [comment]
Tukta request to do this ka

**Comment by deezell1002** [comment]
Chayut ขอจอง
