### ISSUE TITLE
Make navbar sticky

### ISSUE THREAD

**Issue by WiNloSt** [pyladiesbkk/pyladies-web#9]
So that users can navigate through each section easier

**Comment by DCox2016** [comment]
I will take this issue

**Comment by gatukgl** [comment]
Hello @DCox2016,

Thank you for you interesting to contribute PyLadies Bangkok repository. 

We truly appreciate the time and effort that you have put into this issue. We regret to inform you that we cannot accept your contribution now.

We have prepared this repository for the private event `Hacktoberfest 2019: Let's Get Involved in Open Source with PyLadies x Girls Who Dev x DevC by Facebook`.

**Comment by mild20091931** [comment]
Assignees : Mild
